name: NCTL Integration Tests
on:
  workflow_dispatch:
jobs:
  build:
    name: Setting Up NCTL
    runs-on: ubuntu-latest
    services:
      storm-nctl:
        image: makesoftware/casper-nctl:latest
        options: --name storm-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
    steps:
      - name: Starting NCTL docker
        run: |
          echo "Wait for NCTL"
          sleep 30s
          mkdir assets
          docker cp storm-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/chainspec assets
          docker cp storm-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/users assets
          mv assets/users assets/net-1
          mv assets/chainspec assets/net-1/chainspec          

      - name: Upload NCTL assets to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nctl-accounts
          path: |
            assets/net-1/chainspec/accounts.toml
            assets/net-1/user-1/public_key.pem
            assets/net-1/user-1/public_key_pem
            assets/net-1/user-1/secret_key.pem         
            assets/net-1/user-2/public_key.pem
            assets/net-1/user-2/public_key_pem
            assets/net-1/user-2/secret_key.pem      

      - name: Checkout SDK source code
        uses: actions/checkout@v2
        with:
          repository: casper-network/casper-java-sdk
          ref: main
          path: casper-java-sdk

      - name: Setup SDK Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build SDK JAR
        working-directory: casper-java-sdk
        run: ./gradlew clean build

      - name: Upload SDK jar to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: casper-java-sdk-jar
          path: |
            casper-java-sdk/build/libs/*.jar

      - name: Checkout evaluation code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download NCTL assets artifact
        uses: actions/download-artifact@v3
        with:
          name: nctl-accounts

      - name: Download casper-java-sdk-jar artifact
        uses: actions/download-artifact@v3
        with:
          name: casper-java-sdk-jar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Cucumber
        run: |
          mkdir -p assets/net-1
          mv chainspec/ assets/net-1
          mv user-*/ assets/net-1
          cp casper-java-sdk-jar/*.jar libs/
          ls assets -ltra    
          ls libs -ltra    
          ls -ltra          
          ./gradlew clean cucumberCli
