name: NCTL Integration Tests
on:
  workflow_dispatch:
jobs:
  build:
    name: Setting Up NCTL
    runs-on: ubuntu-latest
    services:
      casper-nctl:
        image: makesoftware/casper-nctl:latest
        options: --name casper-nctl
        env:
          PREDEFINED_ACCOUNTS: 'true'
          MINIMUM_ROUND_EXPONENT: '12'
          MAXIMUM_ROUND_EXPONENT: '14'
          DEPLOY_DELAY: '30sec'
        ports:
          - 11101:11101
          - 14101:14101
          - 18101:18101
    steps:
      - name: Setting Up Integration Tests
        run: |
          echo "Wait for NCTL"
          sleep 10s
          docker cp casper-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/chainspec .
          docker cp casper-nctl:/home/casper/casper-node/utils/nctl/assets/net-1/users .
          cat chainspec/accounts.toml

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app_darwin_amd64
          path: |
            chainspec/accounts.toml
            users/user-1/public_key.pem
            users/user-1/public_key_pem
            users/user-1/secret_key.pem         

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: |
          ./gradlew clean cucumberCli
